### ISSUE TITLE
CredentialsProvider does not honor parametrization of DelegabeAuthInfoDAO

### ISSUE THREAD

**Issue by cornerman** [mohiva/play-silhouette#339] opened 2015-05-09 15:20 UTC
We want to use our own AuthInfo Implementation instead of the provided PasswordInfo, but we are stuck with an Exception:
```
...
Caused by: java.lang.Exception: Cannot search for auth info of type: class com.mohiva.play.silhouette.api.util.PasswordInfo
	at com.mohiva.play.silhouette.impl.services.DelegableAuthInfoService.retrieve(DelegableAuthInfoService.scala:71) ~[play-silhouette_2.11-2.0.jar:2.0]
	at com.mohiva.play.silhouette.impl.providers.CredentialsProvider.authenticate(CredentialsProvider.scala:65) ~[play-silhouette_2.11-2.0.jar:2.0]
	at controllers.security.CredentialsAuthController$$anonfun$authenticate$1$$anonfun$apply$1.apply(CredentialsAuthController.scala:26) ~[classes/:na]
	at controllers.security.CredentialsAuthController$$anonfun$authenticate$1$$anonfun$apply$1.apply(CredentialsAuthController.scala:24) ~[classes/:na]
	at play.api.libs.json.JsResult$class.map(JsResult.scala:81) ~[play-json_2.11-2.3.8.jar:2.3.8]
```

As the DelegableAuthInfo is parametrized, we expected this to work and suspect a bug in [CredentialsProvider:65](https://github.com/mohiva/play-silhouette/blob/71637509af168775dbcbb8403e5f8138b342a9cf/silhouette/app/com/mohiva/play/silhouette/impl/providers/CredentialsProvider.scala#L65)

**Comment by akkie** [comment] 2015-05-09 17:42
I'm not really sure what you try to achieve? Could you please provide some code?

**Comment by fdietze** [comment] 2015-05-09 17:59
As we are storing PasswordInfo in our database, we already have a class for that from our database library. We'd like to use this class instead of the one from [PasswordHasher.scala](https://github.com/mohiva/play-silhouette/blob/71637509af168775dbcbb8403e5f8138b342a9cf/silhouette/app/com/mohiva/play/silhouette/api/util/PasswordHasher.scala#L31)

```scala
class PasswordInfoDAO extends DelegableAuthInfoDAO[OurPasswordInfo] {
...
}
```

**Comment by akkie** [comment] 2015-05-09 18:56
This is not a bug but rather a misusage. The CredentialsProvider works only with the PasswordInfo provided by Silhouette and I see really no need to change this. You have two possibilities to use your own class. Either you use your own CredentialsProvider or you map the PasswordInfo to your class before storing or retrieving it from the database. If you use your own CredentialsProvider then you need also your own PasswordHasher implementation, because this depends also on the PasswordInfo.

I don't really understand why you prefer your own implementation over the one provided by Silhouette. Could you please explain this a bit more?

**Comment by akkie** [comment] 2015-05-11 06:54
After reading my last post again, I've noticed that it sounds a bit harsh. Sorry, that wasn't my intention!

Does my suggestion work for you? If not, could you please explain a bit more why you prefer your own implementation over the one provided by Silhouette? Is it only why it's provided by your database library? Or does your implementation add any additional value to your application that the `PasswordInfo` doesn't do?

**Comment by cornerman** [comment] 2015-05-12 14:56
Thanks for the quick response. Now we use the Silhouette PasswordInfo and transform it before writing to and reading from our database. This works! Still, we would have liked to implement our own PasswordInfo trait with the needed properties (hasher, password, salt), as then we could directly use our class without transforming back and forth between the two types.

**Comment by akkie** [comment] 2015-05-12 17:00
This would be possible with a raw type. But this would add unnecessary complexity for the majority of the users. Therefore I close this issue. Thanks for your feedback and your interesst in Silhouette.

**Closed by akkie** 2015-05-12 17:00 UTC
