### ISSUE TITLE
SecureRandomIDGenerator causes problems when fingerprinting is disabled or can't produce unique fingerprints

### ISSUE THREAD

**Issue by AmirKarimi** [mohiva/play-silhouette#329] opened 2015-04-15 08:54 UTC
Reproducing:

- Disable user fingerprinting
- Implement an IDGenerator which always returns the same ID. 
- Create two users A and B
- Login with user A in a browser
- Login with user B in another browser
- Refresh the user A browser
- You get the user B identity

[More info](https://groups.google.com/d/msg/play-silhouette/-e1H5oP4TBs/fnPBL9uo30cJ)

**Comment by akkie** [comment] 2015-04-18 07:45
We need more info to reproduce this issue. As found out in the mailing list, the ID generator isn't the problem. Fingerprinting is also not the issue, because this would only reject a valid authenticator if the client and the authenticator fingerprint are not the same.

**Comment by akkie** [comment] 2015-06-03 14:46
I'll close the issue now. Please open the issue again if you have further information.

**Closed by akkie** 2015-06-03 14:46 UTC
Labels: can't reproduce
